### ISSUE TITLE
Special Spell Timer does not load Placeholders when FFXIV_ACT_Plugin v2.0.3.1 is used

### ISSUE THREAD

**Issue by highlyunavailable** [anoyetta/ACT.Hojoring#238]
**Describe the bug**
Special Spell Timer does not load Placeholders when FFXIV_ACT_Plugin v2.0.3.1 is used due to an API change in FFXIV_ACT_Plugin v2.0.3.1.

**To Reproduce**
1. Update to FFXIV_ACT_Plugin v2.0.3.1
2. Change party composition or zone in FFXIV.
3. Notice that errors appear in the log.

**Screenshots**
N/A

**Environment**
- ACT.Hojoring Version: ACT.Hojoring v7.6.8
- FFXIV_ACT_Plugin Version: FFXIV_ACT_Plugin v2.0.3.1
 - OS: Windows 10

**Additional context**

The stack trace is:

```2019-08-17 15:13:41.1489 [Error] ThreadWorker - scanFFXIVWorker error. System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<FFXIV_ACT_Plugin.Common.Models.NetworkBuff> FFXIV_ACT_Plugin.Common.Models.Combatant.get_NetworkBuffs()'.
   at FFXIV.Framework.XIVHelper.CombatantEx.CopyToEx(Combatant source, CombatantEx destination)
   at FFXIV.Framework.XIVHelper.CombatantsManager.RefreshCore(IEnumerable`1 source, Boolean isDummy)
   at FFXIV.Framework.XIVHelper.CombatantsManager.Refresh(IEnumerable`1 source, Boolean isDummy)
   at FFXIV.Framework.XIVHelper.XIVPluginHelper.RefreshCombatantList()
   at FFXIV.Framework.XIVHelper.XIVPluginHelper.<>c__DisplayClass45_0.<Start>b__1()
   at FFXIV.Framework.Common.ThreadWorker.DoWorkLoop()```

This is because `Combatant` no longer has a `List<NetworkBuff>` property - it is now a field of type `NetworkBuff[]` so there is no more getter.

https://github.com/anoyetta/ACT.Hojoring/blob/master/source/FFXIV.Framework/FFXIV.Framework/XIVHelper/CombatantEx.cs#L73-L77 is the code that is crashing. Additionally, as of FFXIV_ACT_Plugin v2.0.3.1, there is no longer an `UnknownNetworkBuffs` property on `Combatant`.

**Comment by highlyunavailable** [comment]
Closed by efff7f3
