### ISSUE TITLE
Fatal Error. Unhandled Exception. (specialspelltimer)

### ISSUE THREAD

**Issue by hi-im-charlotte** [anoyetta/ACT.Hojoring#243]
issue appears in specialspelltimer

System.MissingMethodException

Method not found: 'Void FFXIV.Framework.Bridge.ConfigBridge.SetUILocaleCallback(System.Func`1<FFXIV.Framework.Globalization.Locales>)'.
   at ACT.TTSYukkuri.PluginCore.<>c__DisplayClass26_0.<<InitPlugin>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at ACT.TTSYukkuri.PluginCore.<>c__DisplayClass26_0.<InitPlugin>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by G0li4th** [comment]
Same issue here. Any solution ?

**Comment by G0li4th** [comment]
Ok I decide to execute powershell script to update instead of doing it manually and now it is OK !
