### ISSUE TITLE
ACT.SpecialSpellTimer plugin init error !

### ISSUE THREAD

**Issue by ViciousBoss** [anoyetta/ACT.Hojoring#244]
After installing the new hojoring 7.7.2 update, I'm receiving the following error when starting up ACT:

**Plugin init error !**

System.InvalidOperationException

There is an error in XML document (0, 0).
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at ACT.SpecialSpellTimer.Models.TagTable.Load()
   at ACT.SpecialSpellTimer.PluginCore.<>c__DisplayClass26_0.<<InitPluginCore>b__0>d.MoveNext()

Inner Exception :
System.Xml.XmlException

Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderTagTable.Read7_TagTable()

**Environment**
- ACT.Hojoring Version: v7.7.2
- FFXIV_ACT_Plugin Version: 2.0.3.2
 - OS: Windows 10

**Comment by z00z9** [comment]
System.InvalidOperationException

There is an error in XML document (0, 0).
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at ACT.SpecialSpellTimer.Models.SpellPanelTable.Load()
   at ACT.SpecialSpellTimer.PluginCore.<>c__DisplayClass26_0.<<InitPluginCore>b__0>d.MoveNext()

Inner Exception :
System.Xml.XmlException

Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderObservableCollection1.Read10_ArrayOfPanelSettings()

Hojoring 7.7.2
SPESPE FileVersion: 2.12.0.0
ACT FileVersion: 2.0.4.0
