### ISSUE TITLE
Plug Int Error

### ISSUE THREAD

**Issue by ZarrZarr** [anoyetta/ACT.Hojoring#263]
**Describe the bug**
When adding the any of the plugins to ACT, It ends up with a Plugin Init error (Have tried it with 3 different installations of ACT) 

**Environment**
- ACT.Hojoring Version: 7.7.2.7+ (Same problem exists in pre release)
- FFXIV_ACT_Plugin Version: 2.0.4.0
 - OS: WIN10

**Additional context**
(all 3 have similar errors)
System.Windows.Markup.XamlParseException

The invocation of the constructor on type 'ACT.TTSYukkuri.Config.Views.GeneralView' that matches the specified binding constraints threw an exception.
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at ACT.TTSYukkuri.Config.Views.ConfigBaseView..ctor()
   at ACT.TTSYukkuri.PluginCore.<>c__DisplayClass27_0.<<InitPlugin>b__0>d.MoveNext()

Inner Exception :
System.InvalidOperationException

There is an error in XML document (0, 0).
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at FFXIV.Framework.Config.Load()
   at FFXIV.Framework.Config.get_Instance()
   at ACT.TTSYukkuri.Config.Views.GeneralView..ctor()

**Comment by TamaZooo** [comment]
`%appdata%\anoyetta\ACT\ACT.TTSYukkuri.config` を削除または、退避してみてください。
多分、このファイルが壊れていることが原因と思われます。
