### ISSUE TITLE
ACT.TTSYukkuri throws errors when launching after v7.15.7 update

### ISSUE THREAD

**Issue by chernobog** [anoyetta/ACT.Hojoring#287]
**Describe the bug**
When launching ACT, after Hojoring loading screen two error messages are displayed. The ACT.TTSYukkuri plugin tab 'YUKKURI' is blank. If the ACT.TTSYukkuri.dll is disabled in the plugins list then no errors are displayed when loading Hojoring. However, YUKKURI still works and uses the default voice.

**To Reproduce**
1. Launch ACT
2. Hojoring splash screen displays
4. Two error messages display:
FIRST ERROR
```
Plugin init error !

Details
System.MissingMethodException

The native method "grpcsharp_slice_buffer_create" does not exist
   at Grpc.Core.Internal.UnmanagedLibrary.GetNativeMethodDelegate[T](String methodName)
   at Grpc.Core.Internal.NativeMethods..ctor(UnmanagedLibrary library)
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at Google.Api.Gax.Grpc.GrpcCore.GrpcCoreAdapter.CreateChannelImpl(String endpoint, ChannelCredentials credentials, GrpcChannelOptions options)
   at Google.Api.Gax.Grpc.ChannelPool.GetChannel(GrpcAdapter grpcAdapter, String endpoint, GrpcChannelOptions channelOptions, ChannelCredentials credentials)
   at Google.Api.Gax.Grpc.ChannelPool.GetChannel(GrpcAdapter grpcAdapter, String endpoint, GrpcChannelOptions channelOptions)
   at Google.Api.Gax.Grpc.ClientBuilderBase`1.CreateCallInvoker()
   at Google.Cloud.TextToSpeech.V1.TextToSpeechClientBuilder.BuildImpl()
   at ACT.TTSYukkuri.Config.GoogleCloudTextToSpeechConfig.<>c.<.cctor>b__37_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at ACT.TTSYukkuri.Config.GoogleCloudTextToSpeechConfig.EnumerateVoice()
   at ACT.TTSYukkuri.Config.GoogleCloudTextToSpeechConfig.set_LanguageCode(String value)
   at ACT.TTSYukkuri.Config.GoogleCloudTextToSpeechConfig.SetRecommend()
   at ACT.TTSYukkuri.Config.Settings..ctor()
   at ACT.TTSYukkuri.Config.Settings.get_Default()
   at ACT.TTSYukkuri.PluginCore.<>c__DisplayClass30_0.<<InitPlugin>b__0>d.MoveNext()
```
SECOND ERROR
```
Fatal Error.
Unhandled Exception.

Details
System.MissingMethodException

The native method "grpcsharp_slice_buffer_create" does not exist
   at Grpc.Core.Internal.UnmanagedLibrary.GetNativeMethodDelegate[T](String methodName)
   at Grpc.Core.Internal.NativeMethods..ctor(UnmanagedLibrary library)
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at Google.Api.Gax.Grpc.GrpcCore.GrpcCoreAdapter.CreateChannelImpl(String endpoint, ChannelCredentials credentials, GrpcChannelOptions options)
   at Google.Api.Gax.Grpc.ChannelPool.GetChannel(GrpcAdapter grpcAdapter, String endpoint, GrpcChannelOptions channelOptions, ChannelCredentials credentials)
   at Google.Api.Gax.Grpc.ChannelPool.GetChannel(GrpcAdapter grpcAdapter, String endpoint, GrpcChannelOptions channelOptions)
   at Google.Api.Gax.Grpc.ClientBuilderBase`1.CreateCallInvoker()
   at Google.Cloud.TextToSpeech.V1.TextToSpeechClientBuilder.BuildImpl()
   at ACT.TTSYukkuri.Config.GoogleCloudTextToSpeechConfig.<>c.<.cctor>b__37_0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at ACT.TTSYukkuri.Config.GoogleCloudTextToSpeechConfig.EnumerateVoice()
   at ACT.TTSYukkuri.Config.GoogleCloudTextToSpeechConfig.set_LanguageCode(String value)
   at ACT.TTSYukkuri.Config.GoogleCloudTextToSpeechConfig.SetRecommend()
   at ACT.TTSYukkuri.Config.Settings..ctor()
   at ACT.TTSYukkuri.Config.Settings.get_Default()
   at ACT.TTSYukkuri.PluginCore.<>c__DisplayClass30_0.<<InitPlugin>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
**Environment**
- ACT.Hojoring Version: v7.15.7 and v7.15.8
- FFXIV_ACT_Plugin Version: 2.0.5.10
 - OS: Windows 10 version 1909

**Comment by TamaZooo** [comment]
`ACTDir` にある`grpc_csharp_ext.x64.dll` と `grpc_csharp_ext.x86.dll` を削除してから、v7.15.8で起動してみて下さい。

**Comment by chernobog** [comment]
After deleting `grpc_csharp_ext.x64.dll` and `grpc_csharp_ext.x86.dll` I still get the errors posted above. The two DLL files also get created again in `C:\Program Files (x86)\Advanced Combat Tracker`.

**Comment by Susanou** [comment]
私も同じエラーがあら。grpc_csharp_ext.x64.dll と grpc_csharp_ext.x86.dll を削除したら何も変わりません。ACTをフルインストールしたらも変わらない。

**Comment by TamaZooo** [comment]
Are you using v7.15.8 or later?

**Comment by Susanou** [comment]
Yes I am using the one most recently released

**Comment by chernobog** [comment]
The v7.15.10 update has resolved this issue for me.
