### ISSUE TITLE
Plugin init error! Yukkuri

### ISSUE THREAD

**Issue by poysama** [anoyetta/ACT.Hojoring#304]
**Describe the bug**
When I add the Yukkuri Plugin, I get an XML parse error. I updated my FFXIV_ACT_Plugin to 2.0.6.0 (Beta for 5.3) which I think might have caused this.

**To Reproduce**
1. Add ACT.TTSYukkuri.ddl to ACT
2. Add/enable plugin

**Screenshots**
None

**Environment**
- ACT.Hojoring Version: 7.17.1
- FFXIV_ACT_Plugin Version: 2.0.6.0
 - OS: Windows 10

**Additional context**
```
System.Windows.Markup.XamlParseException

The invocation of the constructor on type 'ACT.TTSYukkuri.Config.Views.GeneralView' that matches the specified binding constraints threw an exception.
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at ACT.TTSYukkuri.Config.Views.ConfigBaseView..ctor()
   at ACT.TTSYukkuri.PluginCore.<>c__DisplayClass30_0.<<InitPlugin>b__0>d.MoveNext()

Inner Exception :
System.InvalidOperationException

There is an error in XML document (31, 13).
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at FFXIV.Framework.Config.Load()
   at FFXIV.Framework.Config.get_Instance()
   at ACT.TTSYukkuri.Config.Views.GeneralView..ctor()```

**Comment by ionite34** [comment]
I have the same problem as well

**Comment by wbonbon** [comment]
ACT.Hojoring Version 7.17.1 no longer works, please update to 7.18.x
