### ISSUE TITLE
Yukkuri TTS Plugin Init Error: opus.dll

### ISSUE THREAD

**Issue by CasualCoder67** [anoyetta/ACT.Hojoring#309]
**Describe the bug**
When attempting to activate Yukkuri tts an error message saying the plugin was denied access to pus.dll
I checked the library/file location described in the error message and the "opus.dll" file isn't even available.

**To Reproduce**
1. Attempt to add/enable ACT.TTSYukkuri.dll

**Screenshots**
![image](https://user-images.githubusercontent.com/46359977/95682338-a7122300-0bb2-11eb-8c74-74dd0a2ebe5c.png)

**Environment**
- ACT.Hojoring Version: v7.20.15
- FFXIV_ACT_Plugin Version: 2.0.6.8
 - OS: Windows 10 Pro

Error Message Details:
System.UnauthorizedAccessException

Access to the path 'C:\Program Files (x86)\Advanced Combat Tracker\opus.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at ACT.TTSYukkuri.Discord.Models.DiscordNetModel.SetupLibrary()
   at ACT.TTSYukkuri.PluginCore.<>c.<InitPlugin>b__30_4()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ACT.TTSYukkuri.PluginCore.<>c__DisplayClass30_0.<<InitPlugin>b__0>d.MoveNext()

**Comment by steponmepls** [comment]
I had this same error happen to me and I suspect it has something to do with admin permissions. The reason I'm suggesting you this is because I made backup of my ACT settings and plugin configs, uninstalled ACT and used the step by step installation guide as explained [here](https://www.anoyetta.com/entry/hojoring-setup) to fix the problem
I don't know what exactly broke Hojoring but moving ACT out of `Program files` seems to be the key factor.
