### ISSUE TITLE
FATAL ERROR: OnDispatcherUnhandledException()

### ISSUE THREAD

**Issue by Wynix** [anoyetta/ACT.Hojoring#326]
**Describe the bug**
While unspecific time, all my monitors(I'm using 3 monitors) gonna dimmed and all SPESPE's custom triggers are disappeared.
Still ACT are working at that time and it looks work normally before I bring ACT windows to foreground.
But when I bring ACT windows to foreground to see what happend to ACT, it pop up many FATAL ERROR message box in every 0.1 sec.
If I want to stop ACT at that time, I have to force stop ACT process via Task manager.

**To Reproduce**
Unfortunately, I don't know how to reproduce. But I'll attach Hojoring logs when it stuck.

**Screenshots**
I'll attach my logs when Hojoring not works.
[ACT.Hojoring.2021-05-22.log](https://github.com/anoyetta/ACT.Hojoring/files/6527708/ACT.Hojoring.2021-05-22.log)

2021-05-23 00:00:39.9486 [TRACE] ACT.SpecialSpellTimer.PluginMainWorker.BackgroundCore() LPS=26.2 
2021-05-23 00:01:40.0111 [TRACE] ACT.SpecialSpellTimer.PluginMainWorker.BackgroundCore() LPS=25.5 
2021-05-23 00:02:40.0903 [TRACE] ACT.SpecialSpellTimer.PluginMainWorker.BackgroundCore() LPS=22.2 
2021-05-23 00:03:40.1558 [TRACE] ACT.SpecialSpellTimer.PluginMainWorker.BackgroundCore() LPS=21.6 
2021-05-23 00:04:00.0486 [INFO ] FFXIV.Framework.XIVHelper.CombatantsManager.RefreshPartyList() party composition changed. current=LightParty party_count=4 
2021-05-23 00:04:00.6643 [INFO ] FFXIV.Framework.XIVHelper.CombatantsManager.RefreshPartyList() party composition changed. current=LightParty party_count=4 
2021-05-23 00:04:01.4365 [INFO ] FFXIV.Framework.XIVHelper.CombatantsManager.RefreshPartyList() party composition changed. current=Unknown party_count=7 
2021-05-23 00:04:02.2328 [INFO ] FFXIV.Framework.XIVHelper.CombatantsManager.RefreshPartyList() party composition changed. current=FullPartyT2 party_count=8 
2021-05-23 00:04:10.2474 [INFO ] FFXIV.Framework.XIVHelper.CombatantsManager.RefreshPartyList() party composition changed. current=Unknown party_count=7 
2021-05-23 00:04:18.2365 [TRACE] ACT.SpecialSpellTimer.Models.TableCompiler.TryCompile() recompiled triggers on condition changed 
2021-05-23 00:04:18.2365 [TRACE] ACT.SpecialSpellTimer.Models.TableCompiler.TryCompile() zone changed. zone=안갯빛 마을, zone_id=339 
2021-05-23 00:04:18.2915 [FATAL] FFXIV.Framework.Common.WPFHelper.OnDispatcherUnhandledException() Unhandled Exception System.Runtime.InteropServices.COMException (0x88980406): UCEERR_RENDERTHREADFAILURE (Exception from HRESULT: 0x88980406)
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2021-05-23 00:04:18.2915 [FATAL] FFXIV.Framework.Common.WPFHelper.OnDispatcherUnhandledException() Unhandled Exception System.Runtime.InteropServices.COMException (0x88980406): UCEERR_RENDERTHREADFAILURE (Exception from HRESULT: 0x88980406)
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
(and [FATAL] logs are repeated)

**Environment**
- ACT.Hojoring Version: 8.0.11
- FFXIV_ACT_Plugin Version: 2.1.1.9
 - OS: Windows 10 20H2, 19042.985
 - 

**Additional context**

**Comment by wbonbon** [comment]
It seems to occur when the video card device driver crashes (TDR issue)
