### ISSUE TITLE
XamlParserException when attempting to load plugin on Windows 11.

### ISSUE THREAD

**Issue by jwshive** [anoyetta/ACT.Hojoring#339]
**Describe the bug**
When attempting to load the plugin, I am receiving a System.Windows.Markup.XamlParseException error.

**To Reproduce**
[ have previously installed versions at or higher for the Microsoft Visual C++ redistributable package and .NET Framework 4.8]
1. Go to 'plugins'
2. Click on 'browse'
3. Find ACT.SpecialSpellTimer.dll in extracted plugin folder
4. Click Add/Enable plugin
5. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/135413/140651027-a7e4a3d2-950f-443b-8b71-5875ed8a9643.png)

**Environment**
- ACT.Hojoring Version: ACT.Hojoring-v9.3.5 (same error with 9.3.6)
- FFXIV_ACT_Plugin Version: 2.12.0.0
 - OS: 
 Windows Edition	Windows 11 Pro
Version	21H2
Installed on	‎8/‎12/‎2021
OS build	22000.282
Experience	Windows Feature Experience Pack 1000.22000.282.0

**Additional context**
System.Windows.Markup.XamlParseException

The invocation of the constructor on type 'ACT.SpecialSpellTimer.Config.Views.SpellPanelConfigView' that matches the specified binding constraints threw an exception.
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at ACT.SpecialSpellTimer.PluginCore.<>c__DisplayClass26_0.<<InitPluginCore>b__0>d.MoveNext()

Inner Exception :
System.ArgumentException

ResourceDictionary LoadFrom operation failed with URI ''''.
   at System.Windows.ResourceDictionary.set_Source(Uri value)
   at ACT.SpecialSpellTimer.resources.LocalizeExtensions.ReloadLocaleDictionary[T](T element, Locales locale)
   at ACT.SpecialSpellTimer.Config.Views.SpellPanelConfigView..ctor()

More than willing to help test fixes/builds on windows 11.

**Comment by wbonbon** [comment]
You probably don't have an extract/place resource folder.
![image](https://i.imgur.com/f3FTmvY.png)

**Comment by jwshive** [comment]
You're right. It was a bad 7zip extraction every time. I had to install the windows gui to get it right.
