### ISSUE TITLE
Fatal Error - Unhandled Exception and Special.Spellspeed plugin fails to load

### ISSUE THREAD

**Issue by StellarJay77** [anoyetta/ACT.Hojoring#343]
After 6.0 update Special.Spellspeed plugin fails to initialize so I disabled it. Well waiting in queue to log in ACT throws the following error:

---------------------------
Fatal Error - Unhandled Exception
---------------------------
An unhandled exception has occurred.  ACT may close.
Press Ctrl-C to copy this MessageBox.

System.TypeInitializationException - The type initializer for 'FFXIV.Framework.XIVHelper.CombatantsManager' threw an exception.
   at FFXIV.Framework.Common.EnvironmentHelper.<>c.<StartActivator>b__27_0()

   at ACT.Hojoring.Activator.ActivationManager.<RefreshAccountList>d__24.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

FFXIV.Framework.Common.EnvironmentHelper+<>c, FFXIV.Framework, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null
---------------------------
OK   
---------------------------

I click okay and it closes ACT

**Comment by exeedz** [comment]
check the hojoring's main folder, if you found FFXIV.Framework delete those 2. Hojoring v10 (for endwalker) put that file in different folder now, so the one in main folder can be removed safely

**Comment by StellarJay77** [comment]
Emptied out the whole Hojoring Plugin folder into a backup and then Unzipped a freshly downloaded copy into it and still getting the same fatal error. Also ACT.SpecialSpellTimer plugin throws the following error: Plugin init error

System.Windows.Markup.XamlParseException

The invocation of the constructor on type 'ACT.SpecialSpellTimer.Config.ViewModels.SpellConfigViewModel' that matches the specified binding constraints threw an exception.
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at ACT.SpecialSpellTimer.PluginCore.<InitPluginCore>d__26.MoveNext()

Inner Exception :
System.TypeLoadException

Could not load type 'FFXIV_ACT_Plugin.Common.Models.PartyType' from assembly 'FFXIV_ACT_Plugin.Common, Version=2.2.0.5, Culture=neutral, PublicKeyToken=9f740ac505d6bc50'.
   at ACT.SpecialSpellTimer.Models.TableCompiler..ctor()
   at ACT.SpecialSpellTimer.Models.TableCompiler.get_Instance()
   at ACT.SpecialSpellTimer.Config.ViewModels.SpellConfigViewModel.SwitchDesignGrid()
   at ACT.SpecialSpellTimer.Config.ViewModels.SpellConfigViewModel.set_Model(Spell value)
   at ACT.SpecialSpellTimer.Config.ViewModels.SpellConfigViewModel..ctor(Spell model)

**Comment by StellarJay77** [comment]
The Fatal Error doesn't happen right away either, it takes ~30 seconds for it to show up.

**Comment by exeedz** [comment]
ahh i think you need a new ACT FFXIV plugin version (2.6.2.0)

**Comment by kagekitsune** [comment]
were do we get 2.6.2.0? im getting the same error act doesn't have an update to the plugin and i cant find it on google

**Comment by StellarJay77** [comment]
I relaunched the wizard and reinstalled the latest FFXIV parsing plugin. Still same error

**Comment by exeedz** [comment]
can you screenshot your plugin list or the current error? the latest ACT FFXIV (BETA v2.6.2.1) plugin is in its discord only

**Comment by StellarJay77** [comment]
I upgraded to the latest beta and all is well now again. For others link is [here](https://cdn.discordapp.com/attachments/551476805148737546/916725505238126612/FFXIV_ACT_Plugin_2.6.2.1.zip).
