### ISSUE TITLE
Plugin init error

### ISSUE THREAD

**Issue by Elodette** [anoyetta/ACT.Hojoring#348]
Ever since I updated ACT a few days ago, my special spell timer plugin won't open and shows "plugin init error."  I tried moving my entire ACT folder to just C: and also tried to update manually by running the Hojoring updater.  The error still keeps popping up. Anything else I can do?

![SSPE Error](https://user-images.githubusercontent.com/95870751/145427321-c9bff3ad-63f6-47b7-87fe-23c307fb1a95.png)
![special spell timer error 2](https://user-images.githubusercontent.com/95870751/145427644-40ec9592-45e8-4447-bc15-0c927963f524.png)

**Comment by wbonbon** [comment]
%appdata%\anoyetta\ACT\ACT.SpecialSpellTimer.config
Maybe this file is corrupted
Delete or use backup

**Comment by Krojack** [comment]
I just had this error while launching ACT. Restoring a backup of the config didn't fix it. I then re-downloaded the entire .7z file, renamed my old "Hojoring" folder to "Hojoring-OLD" and then copied the extracted .7z file over. Relaunched ACT and it went though the downloading of resources and no more error. I didn't touch any of the saved config files in the "% Appdata% \anoyetta\ACT\" folder so I still had all my previous settings.

The following is from the startup log file for this ACT plugin and where it crashed out.

```
<SNIP Lots of checked files before this point>

2022-05-20 22:04:45.1995 [INFO ] FFXIV.Framework.resources.ResourcesDownloader.DownloadAsync() Checking... N:\ACTv3\plugins\Hojoring\resources\xivdb\TerritoryType.fr-FR.csv. It was up-to-date. 
2022-05-20 22:04:45.1995 [INFO ] FFXIV.Framework.resources.ResourcesDownloader.DownloadAsync() Checking... N:\ACTv3\plugins\Hojoring\resources\xivdb\TerritoryType.ja-JP.csv. It was up-to-date. 
2022-05-20 22:04:45.2165 [INFO ] FFXIV.Framework.resources.ResourcesDownloader.DownloadAsync() Checking... N:\ACTv3\plugins\Hojoring\resources\xivdb\TerritoryType.ko-KR.csv. It was up-to-date. 
2022-05-20 22:04:45.2395 [ERROR] ACT.SpecialSpellTimer.Utility.Logger.Write() InitPlugin error. System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderSettings.Read6_Settings()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at ACT.SpecialSpellTimer.Config.Settings.Load()
   at ACT.SpecialSpellTimer.PluginCore.<InitPluginCore>d__26.MoveNext()
```

The following is from the log of a successful loading without errros

```
2022-05-20 22:27:06.1455 [INFO ] FFXIV.Framework.resources.ResourcesDownloader.DownloadAsync() Downloaded... N:\ACTv3\plugins\Hojoring\resources\xivdb\TerritoryType.ja-JP.csv, verify is completed. 
2022-05-20 22:27:06.3756 [INFO ] FFXIV.Framework.resources.ResourcesDownloader.DownloadAsync() Downloaded... N:\ACTv3\plugins\Hojoring\resources\xivdb\TerritoryType.ko-KR.csv, verify is completed. 
2022-05-20 22:27:08.6491 [TRACE] ACT.SpecialSpellTimer.PluginCore.InitPluginCore() [SPESPE] End InitPlugin 
2022-05-20 22:27:08.6801 [TRACE] FFXIV.Framework.XIVHelper.XIVApi.LoadBuff() xivapi status list loaded. N:\ACTv3\plugins\Hojoring\resources\xivdb\Status.en-US.csv 
2022-05-20 22:27:09.2942 [TRACE] FFXIV.Framework.XIVHelper.XIVApi.LoadAction() xivapi action list loaded. 1s N:\ACTv3\plugins\Hojoring\resources\xivdb\Action.en-US.csv 
2022-05-20 22:27:09.2942 [TRACE] ACT.SpecialSpellTimer.PluginMainWorker+<>c.<Begin>b__24_1() start trigger compiler. 
2022-05-20 22:27:09.2942 [TRACE] FFXIV.Framework.Common.ThreadWorker.DoWorkLoop() ThreadWorker - detectLogsWorker start. 
2022-05-20 22:27:09.3272 [TRACE] FFXIV.Framework.Common.ThreadWorker.DoWorkLoop() ThreadWorker - sharlayan Memory Subscriber start. 
```
This lead me to believe that the error was a file within the plugin install that went bad thus a redownload and install.
