### ISSUE TITLE
Unhandled Exception in ACT (Happens on start up)

### ISSUE THREAD

**Issue by SilverSun247** [anoyetta/ACT.Hojoring#359]
On boot up Yukkuri and the other Hojoring plugins fail to boot and cannot be enabled.
This is the error I receive. I've tried a few things like totally uninstalling and reinstalling but it is still persisting.

System.Xml.XmlException - '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at FFXIV.Framework.Config.MigrateConfig(String file)
   at FFXIV.Framework.Config.Load()
   at FFXIV.Framework.Config.get_Instance()
   at FFXIV.Framework.Common.CommonSounds.PlayWave(String fileName)
   at FFXIV.Framework.WPF.Views.ModernMessageBox.ShowDialog(String message, String caption, MessageBoxButton button, Exception ex)
   at ACT.TTSYukkuri.PluginCore.<InitPlugin>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

System.Xml.XmlTextReaderImpl, System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089

**Comment by msang710** [comment]
got a exactly same issue
![캡처](https://user-images.githubusercontent.com/105012639/166987241-ae7f2362-ded8-46a6-9135-a3496957fa92.PNG)

**Comment by wbonbon** [comment]
https://github.com/anoyetta/ACT.Hojoring/wiki/FAQ-jp#Fatal-Error---Unhandled-Exception%E3%81%8C%E8%A1%A8%E7%A4%BA%E3%81%95%E3%82%8C%E3%82%8B
