### ISSUE TITLE
Constant exceptions from new OverlayPlugin log lines

### ISSUE THREAD

**Issue by quisquous** [anoyetta/ACT.Hojoring#366]
OverlayPlugin has added new log line types that are not in the ffxiv plugin.  When using [OverlayPlugin 0.19.5](https://github.com/OverlayPlugin/OverlayPlugin/releases/tag/v0.19.5) this causes constant exceptions in this code: <https://github.com/anoyetta/ACT.Hojoring/blob/master/source/FFXIV.Framework/FFXIV.Framework/XIVHelper/LogMessageTypeExtensions.cs#L10-L25>

Copying Zeffuro's report [from discord](https://discord.com/channels/551474815727304704/551892582855344128/1021568215492599999):

```
***** 2022-09-19T19:46:54 - OnLogLineRead event
258|2022-09-19T19:46:54.6179420-04:00|Update|203A|00000287|00000000|00000000|00000000|00000000|00000000|6E756F63|bd60bac0189b571e
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at FFXIV.Framework.XIVHelper.LogMessageTypeExtensions.RemoveLogMessageType(LogMessageType type, String logLine, Boolean withoutTimestamp)
   at FFXIV.Framework.XIVHelper.XIVPluginHelper.OnLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
   at Advanced_Combat_Tracker.FormActMain.ParseRawLogLine(Boolean isImport, DateTime ParsedLogTime, String LogLine, String CompanionLogName)
   at Advanced_Combat_Tracker.FormActMain.WriteExceptionLog(Exception ex, String MoreInfo)
   at Advanced_Combat_Tracker.FormActMain.ParseRawLogLine(Boolean isImport, DateTime ParsedLogTime, String LogLine, String CompanionLogName)
   at Advanced_Combat_Tracker.FormActMain.ReadLog()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
*****
```

**Comment by quisquous** [comment]
I've disabled this behavior in OverlayPlugin 0.19.6 but only temporarily so that Hojoring users are not having constant exceptions.  However, I would like to turn this back on as soon as possible.

To give more details about the above, OverlayPlugin 0.19.5 is adding new log lines that the ffxiv plugin does not know about.  These log line ids are not in `LogMessageType` intentionally.  These log lines have ids that start at 256 and go up, with log ids of 255 and below being reserved for the ffxiv plugin.  Because Hojoring throws exceptions when a log line appears that is not in `LogMessageType` this causes many exceptions.  I think Hojoring should be updated to not throw exceptions, and possibly ignore these lines entirely.

valarnin has mentioned [in discord](https://discord.com/channels/551474815727304704/551892582855344128/1021578540413616128) that this might be a possible fix, but they have not tested this:

```csharp
        public static string ToStringEx(
            this LogMessageType type)
            => LazyLogMessageTypeTextStore.Value.ContainsKey(type) ? LazyLogMessageTypeTextStore.Value[type] : type.ToString();
```
