### ISSUE TITLE
Discord Bot randomly Disconnects and Reconnects

### ISSUE THREAD

**Issue by FrUct1s** [anoyetta/ACT.Hojoring#380]
Discord Bot randomly throws an error out and disconnects from Discord Voice chat - reconnects after a few seconds

Can't reproduce, seems random but happens every day, even when I'm not feeding TTS through the Discord Bot

```
2023-03-06 19:29:49.5674 [Error] [DISCORD] Join Voice Channel Error. System.Threading.ThreadStateException: Thread is running or terminated; it cannot restart.
   at System.Threading.Thread.StartupSetApartmentStateInternal()
   at System.Threading.Thread.Start(StackCrawlMark& stackMark)
   at System.Threading.Thread.Start()
   at ACT.TTSYukkuri.Discord.Models.DiscordNetModel.<JoinVoiceChannel>d__47.MoveNext()
2023-03-06 20:04:00.5921 [Error] SpeakTTS で例外が発生しました。 System.FormatException: XML content not valid. ---> System.Xml.XmlException: An error occurred while parsing EntityName. Line 1, position 191.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseEntityName()
   at System.Xml.XmlTextReaderImpl.ParseEntityReference()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Speech.Internal.Synthesis.SsmlParser.ProcessElement(XmlReader reader, ISsmlParser engine, String sElement, SsmlElement possibleElements, SsmlAttributes ssmAttributesParent, Boolean fIgnore, List`1 extraAttributes)
   at System.Speech.Internal.Synthesis.SsmlParser.ParseProsody(XmlReader reader, ISsmlParser engine, SsmlElement element, SsmlAttributes ssmAttributesParent, Boolean fIgnore)
   at System.Speech.Internal.Synthesis.SsmlParser.ProcessElement(XmlReader reader, ISsmlParser engine, String sElement, SsmlElement possibleElements, SsmlAttributes ssmAttributesParent, Boolean fIgnore, List`1 extraAttributes)
   at System.Speech.Internal.Synthesis.SsmlParser.ParseVoice(XmlReader reader, ISsmlParser engine, SsmlElement element, SsmlAttributes ssmAttributesParent, Boolean fIgnore)
   at System.Speech.Internal.Synthesis.SsmlParser.ProcessElement(XmlReader reader, ISsmlParser engine, String sElement, SsmlElement possibleElements, SsmlAttributes ssmAttributesParent, Boolean fIgnore, List`1 extraAttributes)
   at System.Speech.Internal.Synthesis.SsmlParser.ProcessSpeakElement(XmlReader reader, ISsmlParser engine, Object voice)
   at System.Speech.Internal.Synthesis.SsmlParser.Parse(XmlReader reader, ISsmlParser engine, Object voice)
   --- End of inner exception stack trace ---
   at System.Speech.Internal.Synthesis.VoiceSynthesis.Speak(Prompt prompt)
   at ACT.TTSYukkuri.SAPI5.SAPI5SpeechController.<>c__DisplayClass9_0.<Speak>b__0()
   at ACT.TTSYukkuri.SpeechControllerExtentions.CreateWaveWrapper(ISpeechController speechController, String wave, Action action)
   at ACT.TTSYukkuri.SAPI5.SAPI5SpeechController.Speak(String text, PlayDevices playDevice, VoicePalettes voicePalette, Boolean isSync, Nullable`1 volume)
   at ACT.TTSYukkuri.PluginCore.SpeakTTS(String textToSpeak, PlayDevices playDevice, VoicePalettes voicePalette, Boolean isSync, Nullable`1 volume)
2023-03-06 20:04:10.6861 [Error] SpeakTTS で例外が発生しました。 System.FormatException: XML content not valid. ---> System.Xml.XmlException: An error occurred while parsing EntityName. Line 1, position 191.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseEntityName()
   at System.Xml.XmlTextReaderImpl.ParseEntityReference()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Speech.Internal.Synthesis.SsmlParser.ProcessElement(XmlReader reader, ISsmlParser engine, String sElement, SsmlElement possibleElements, SsmlAttributes ssmAttributesParent, Boolean fIgnore, List`1 extraAttributes)
   at System.Speech.Internal.Synthesis.SsmlParser.ParseProsody(XmlReader reader, ISsmlParser engine, SsmlElement element, SsmlAttributes ssmAttributesParent, Boolean fIgnore)
   at System.Speech.Internal.Synthesis.SsmlParser.ProcessElement(XmlReader reader, ISsmlParser engine, String sElement, SsmlElement possibleElements, SsmlAttributes ssmAttributesParent, Boolean fIgnore, List`1 extraAttributes)
   at System.Speech.Internal.Synthesis.SsmlParser.ParseVoice(XmlReader reader, ISsmlParser engine, SsmlElement element, SsmlAttributes ssmAttributesParent, Boolean fIgnore)
   at System.Speech.Internal.Synthesis.SsmlParser.ProcessElement(XmlReader reader, ISsmlParser engine, String sElement, SsmlElement possibleElements, SsmlAttributes ssmAttributesParent, Boolean fIgnore, List`1 extraAttributes)
   at System.Speech.Internal.Synthesis.SsmlParser.ProcessSpeakElement(XmlReader reader, ISsmlParser engine, Object voice)
   at System.Speech.Internal.Synthesis.SsmlParser.Parse(XmlReader reader, ISsmlParser engine, Object voice)
   --- End of inner exception stack trace ---
   at System.Speech.Internal.Synthesis.VoiceSynthesis.Speak(Prompt prompt)
   at ACT.TTSYukkuri.SAPI5.SAPI5SpeechController.<>c__DisplayClass9_0.<Speak>b__0()
   at ACT.TTSYukkuri.SpeechControllerExtentions.CreateWaveWrapper(ISpeechController speechController, String wave, Action action)
   at ACT.TTSYukkuri.SAPI5.SAPI5SpeechController.Speak(String text, PlayDevices playDevice, VoicePalettes voicePalette, Boolean isSync, Nullable`1 volume)
   at ACT.TTSYukkuri.PluginCore.SpeakTTS(String textToSpeak, PlayDevices playDevice, VoicePalettes voicePalette, Boolean isSync, Nullable`1 volume)
2023-03-06 20:04:19.6953 [Error] SpeakTTS で例外が発生しました。 System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at NAudio.FileFormats.Wav.WaveFileChunkReader.ReadRiffHeader(BinaryReader br)
   at NAudio.FileFormats.Wav.WaveFileChunkReader.ReadWaveHeader(Stream stream)
   at NAudio.Wave.WaveFileReader..ctor(Stream inputStream, Boolean ownInput)
   at NAudio.Wave.AudioFileReader.CreateReaderStream(String fileName)
   at NAudio.Wave.AudioFileReader..ctor(String fileName)
   at FFXIV.Framework.Common.BufferedWavePlayer.PlayerSet.ReadWaveSamples(String file, Single volume)
   at FFXIV.Framework.Common.BufferedWavePlayer.PlayerSet.Play(String file, Single volume, Boolean sync)
   at FFXIV.Framework.Common.WavePlayer.Play(String file, Single volume, WavePlayerTypes playerType, String deviceID, Boolean sync)
   at ACT.TTSYukkuri.SoundPlayerWrapper.PlayCore(String file, Single volume, WavePlayerTypes playerType, String deviceID, Boolean isSync)
   at ACT.TTSYukkuri.SoundPlayerWrapper.Play(String waveFile, PlayDevices playDevice, Boolean isSync, Nullable`1 volume)
   at ACT.TTSYukkuri.PluginCore.SpeakTTS(String textToSpeak, PlayDevices playDevice, VoicePalettes voicePalette, Boolean isSync, Nullable`1 volume)
```

**Environment**
- ACT.Hojoring Version: v10.2.5
- FFXIV_ACT_Plugin Version: v2.6.8.0
 - OS: Windows 11

**Comment by FrUct1s** [comment]
```
[2023-03-21 20:00:23.5787] Join Voice Channel Error.
System.TimeoutException: The operation has timed out.
   at Discord.WebSocket.SocketGuild.<ConnectAudioAsync>d__190.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.WebSocket.SocketGuild.<ConnectAudioAsync>d__190.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.WebSocket.SocketVoiceChannel.<ConnectAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ACT.TTSYukkuri.Discord.Models.DiscordNetModel.<JoinVoiceChannel>d__47.MoveNext()
[2023-03-21 20:01:46.0413] Join Voice Channel Error.
System.TimeoutException: The operation has timed out.
   at Discord.WebSocket.SocketGuild.<ConnectAudioAsync>d__190.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.WebSocket.SocketGuild.<ConnectAudioAsync>d__190.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.WebSocket.SocketVoiceChannel.<ConnectAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ACT.TTSYukkuri.Discord.Models.DiscordNetModel.<JoinVoiceChannel>d__47.MoveNext()
```

**Comment by cythrawll** [comment]
Same
```
2023-03-21 22:48:02.2647] Join Voice Channel Error.
System.TimeoutException: The operation has timed out.
   at Discord.WebSocket.SocketGuild.<ConnectAudioAsync>d__190.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.WebSocket.SocketGuild.<ConnectAudioAsync>d__190.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.WebSocket.SocketVoiceChannel.<ConnectAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ACT.TTSYukkuri.Discord.Models.DiscordNetModel.<JoinVoiceChannel>d__47.MoveNext()
[2023-03-21 22:50:35.1284] Join Voice Channel Error.
System.TimeoutException: The operation has timed out.
   at Discord.WebSocket.SocketGuild.<ConnectAudioAsync>d__190.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.WebSocket.SocketGuild.<ConnectAudioAsync>d__190.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.WebSocket.SocketVoiceChannel.<ConnectAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ACT.TTSYukkuri.Discord.Models.DiscordNetModel.<JoinVoiceChannel>d__47.MoveNext()
[2023-03-21 22:51:00.9466] Join Voice Channel Error.
System.TimeoutException: The operation has timed out.
   at Discord.WebSocket.SocketGuild.<ConnectAudioAsync>d__190.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.WebSocket.SocketGuild.<ConnectAudioAsync>d__190.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.WebSocket.SocketVoiceChannel.<ConnectAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ACT.TTSYukkuri.Discord.Models.DiscordNetModel.<JoinVoiceChannel>d__47.MoveNext()
[2023-03-21 22:51:45.1564] Join Voice Channel Error.
System.TimeoutException: The operation has timed out.
   at Discord.WebSocket.SocketGuild.<ConnectAudioAsync>d__190.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.WebSocket.SocketGuild.<ConnectAudioAsync>d__190.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.WebSocket.SocketVoiceChannel.<ConnectAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ACT.TTSYukkuri.Discord.Models.DiscordNetModel.<JoinVoiceChannel>d__47.MoveNext()
```

**Comment by wbonbon** [comment]
次のリリースで修正されます #383
