### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by dark0past** [anoyetta/ACT.Hojoring#57]
Hello, i cannot use triggers with this plugin, it will get in error while calling mechanics in FFXIV and close ACT.

Application-Start 2018-03-15T21:56:53 (v3.3.1     Release: 256 | CLR v4.0.30319.42000 | OS Microsoft Windows NT 6.2.9200.0)
***** 2018-03-15T21:56:54 - Entering InitACT
***** 2018-03-15T21:56:54 - Entering LoadNewSettings
***** 2018-03-15T21:56:54 - Config loading plugin from: F:\Advanced Combat Tracker\FFXIV_ACT_Plugin.dll
***** 2018-03-15T21:56:54 - Config loading plugin from: F:\Advanced Combat Tracker\Build\OverlayPlugin.dll
***** 2018-03-15T21:56:54 - Config loading plugin from: C:\Program Files (x86)\Advanced Combat Tracker\ACT.Hojoring-v5.3.8\ACT.TTSYukkuri.dll
***** 2018-03-15T21:56:54 - Enabling plugin: C:\Program Files (x86)\Advanced Combat Tracker\ACT.Hojoring-v5.3.8\ACT.TTSYukkuri.dll
***** 2018-03-15T21:56:55 - Exiting LoadNewSettings
***** 2018-03-15T21:56:55 - LogFileChanged: C:\Users\User\AppData\Roaming\Advanced Combat Tracker\FFXIVLogs\Network_20180315.log - 2018-03-15T19:58:18 - 2018-03-15T21:11:06 - 3158
***** 2018-03-15T21:56:55 - BeforeLogLineRead is not handled
***** 2018-03-15T21:57:00 - Checking for program updates
***** 2018-03-15T21:57:00 - Exiting InitACT: 5988.75
*****
2018-03-15T22:04:13
Unhandled Exception
System.InvalidOperationException: The connection is not initialized
   at DSharpPlus.VoiceNext.VoiceNextConnection.<SendSpeakingAsync>d__159.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DSharpPlus.VoiceNext.VoiceNextConnection.<SendAsync>d__157.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ACT.TTSYukkuri.Discord.Models.WaveModel.<SendEncode>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
*****
Application-Close 2018-03-15T22:04:37
***** 2018-03-15T22:04:37 - Entering SaveNewSettings

**Comment by anoyetta** [comment]
libsodium.dll, libopus.dll が、ACTのインストールディレクトリに配置されていないのではないでしょうか？

**Comment by dark0past** [comment]
![capture](https://user-images.githubusercontent.com/12001903/37519947-316cb6c6-292c-11e8-8ad2-e8f62950a074.JPG)

yes it is already there. The plug in works, but it gets error and closes in the middle of the raid fight.

**Comment by anoyetta** [comment]
https://github.com/anoyetta/ACT.Hojoring/issues/7

レイドなどで本格的に使用するには仮想サウンドミキサ、サウンドカードを使用すると良いでしょう。
