### ISSUE TITLE
Discord error

### ISSUE THREAD

**Issue by sethi12345** [anoyetta/ACT.Hojoring#69]
Play Sound Error. System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.Monitor.ObjWait(Boolean exitContext, Int32 millisecondsTimeout, Object obj)
   at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.SpinThenBlockingWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.InternalWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Audio.AudioStream.Flush()
   at ACT.TTSYukkuri.Discord.Models.DiscordNetModel.PlayCore(String audioFile)

[ACT.Hojoring.HelpMe.2018-06-06.zip](https://github.com/anoyetta/ACT.Hojoring/files/2078568/ACT.Hojoring.HelpMe.2018-06-06.zip)

**Comment by anoyetta** [comment]
i cant reproduced this issue.

**Comment by anoyetta** [comment]
please tell me details of the reproduction condition and procedure.
If it can not be reproduced, it can not investigate.

**Comment by vin10630** [comment]
1. Join to voice channel the of Discord.
2. Generate sound from sub device.
  e.g. Notify TTS from SPESPE.
3. unable sound from sub device.
4. Leave from Discord.
5. Displayed sethi12345's message.

*Enabled sub device by Use Discord.

**Comment by vin10630** [comment]
Do you have a any update? This issue happening also v5.11.1.
I went rollback to v5.8.2, It was normal working.

**Comment by vin10630** [comment]
I get an error when using Discord bot on the timeline.
<default target-element="Activity" target-attr="notice-d" value="Both" />

**Comment by vin10630** [comment]
##<default target-element="Activity" target-attr="notice-d" value="Both" />##

**Comment by anoyetta** [comment]
you upgrade to Windows 10.
